//USER REQUESTS
GET http://localhost:5119/
###
GET http://localhost:5119/users
###
POST  http://localhost:5119/signin
content-type: application/json

{
    "Id" : 1,
    "Name" : "del me",
    "Email" : "eashimwe@gmail.com",
    "Password" : "12345"
}
###
DELETE http://localhost:5119/users/2
###
GET http://localhost:5119/login

content-type: application/json
{
    "Id" : 1
}
###
//car requests 
GET http://localhost:5119/cars
###
POST  http://localhost:5119/cars
content-type: application/json

{
    "Id" : 2,
    "Make" : "del car",
    "Model" : "4567",
    "Year" : "1213",
    "OwnerId" : "1"
}
###
DELETE http://localhost:5119/cars/2
###
GET http://localhost:5119/cars/1
###
//image requests
GET http://localhost:5119/images
###
POST  http://localhost:5119/images
content-type: application/json

{
    "Id" : 2,
    "ImageUrl" : "del image",
    "CarId" : "1"
}
###
DELETE http://localhost:5119/images/2
###
GET http://localhost:5119/images/1



